import { randomUUID } from 'node:crypto';
import { z } from 'zod';
import { PlatformError, defineCommand, type CommandContext, type Tx } from '@storeweave/contracts';
import { recordRefundResultInput, refundDto, requestFullRefundInput, retryRefundInput, type RefundDto } from './dto';
import { RefundRepository,toRefundDto } from './repository';
import { refundFailedV1,refundRequestedV1,refundSucceededV1 } from './events';
const repository=new RefundRepository();
export interface RefundOrderLookup { paymentForRefund(tx:Tx,orderId:string):Promise<{orderId:string;customerId:string|null;currency:string;amountCents:number;paymentAttemptId:string;paymentAttemptRef:string;paymentProvider:string;paymentProviderRef:string}>; finalizeDirectRefund(ctx:CommandContext,orderId:string):Promise<void>; }
export interface RefundShipmentLookup { hasShipmentForOrder(tx:Tx,orderId:string):Promise<boolean>; }
async function directAllowed(ctx:CommandContext,orderId:string,orders:RefundOrderLookup,shipments:RefundShipmentLookup){const payment=await orders.paymentForRefund(ctx.tx,orderId);if(await shipments.hasShipmentForOrder(ctx.tx,orderId))throw PlatformError.conflict(`Order ${orderId} has entered fulfilment; direct refunds are decided by RMA`);return payment;}
const eventPayload=(d:RefundDto,now:Date,paymentProviderRef:string)=>({refundId:d.id,orderId:d.orderId,source:d.source,sourceRef:d.sourceRef,amountCents:d.amountCents,currency:d.currency,paymentProvider:d.paymentProvider,paymentProviderRef,providerRequestRef:d.providerRequestRef,attemptNo:d.attemptNo,occurredAt:now});
export const requestFullRefundCommand=defineCommand({name:'commerce.refund.requestFullRefund',summary:'請求未出貨已付款訂單的整單退款',input:requestFullRefundInput,output:refundDto,permission:'refund:write',idempotency:'required',audit:{action:'refund.requested',resourceType:'refund',resourceId:(_i,o:RefundDto)=>o.id,redact:i=>({orderId:i.orderId,reason:i.reason})}});
export function createRequestFullRefundHandler(orders:RefundOrderLookup,shipments:RefundShipmentLookup){return async(input:z.infer<typeof requestFullRefundInput>,ctx:CommandContext):Promise<RefundDto>=>{const p=await directAllowed(ctx,input.orderId,orders,shipments);if(await repository.hasDirectRefund(ctx.tx,input.orderId))throw PlatformError.conflict(`Order ${input.orderId} already has a direct refund; retry its failed record instead`);return createRmaOrDirectRefund(ctx,{...p,source:'direct',sourceRef:null,reason:input.reason});};}
/** Internal RMA boundary. An RMA supplies the locked payment snapshot and is its own idempotency source. */
export async function createRmaRefund(ctx:CommandContext,input:{rmaId:string;orderId:string;customerId:string|null;currency:string;amountCents:number;paymentAttemptId:string;paymentAttemptRef:string;paymentProvider:string;paymentProviderRef:string;reason:string}):Promise<RefundDto>{const existing=await repository.findRmaRefund(ctx.tx,input.rmaId);if(existing)return toRefundDto(existing);return createRmaOrDirectRefund(ctx,{...input,source:'rma',sourceRef:input.rmaId});}
async function createRmaOrDirectRefund(ctx:CommandContext,input:{orderId:string;customerId:string|null;currency:string;amountCents:number;paymentAttemptId:string;paymentAttemptRef:string;paymentProvider:string;paymentProviderRef:string;source:'direct'|'rma';sourceRef:string|null;reason:string}):Promise<RefundDto>{const id=randomUUID();const row=await repository.insert(ctx.tx,{id,orderId:input.orderId,customerId:input.customerId,source:input.source,sourceRef:input.sourceRef,originalPaymentAttemptId:input.paymentAttemptId,originalPaymentAttemptRef:input.paymentAttemptRef,paymentProvider:input.paymentProvider,paymentProviderRef:input.paymentProviderRef,amountCents:input.amountCents,currency:input.currency,reason:input.reason,requestedByActorId:ctx.actor.id,status:'requested',attemptNo:1,providerRequestRef:`refund:${id}`,requestedAt:ctx.now,updatedAt:ctx.now});const dto=toRefundDto(row);await ctx.publish({name:refundRequestedV1.name,payload:eventPayload(dto,ctx.now,input.paymentProviderRef)});return dto;}
export const retryRefundCommand=defineCommand({name:'commerce.refund.retryRefund',summary:'重試被 provider 明確拒絕的退款',input:retryRefundInput,output:refundDto,permission:'refund:write',idempotency:'required',audit:{action:'refund.retried',resourceType:'refund',resourceId:i=>i.id}});
export function createRetryRefundHandler(orders:RefundOrderLookup,shipments:RefundShipmentLookup){return async(input:z.infer<typeof retryRefundInput>,ctx:CommandContext):Promise<RefundDto>=>{const existing=await repository.findById(ctx.tx,input.id);if(!existing)throw PlatformError.notFound('Refund',input.id);if(existing.source==='direct')await directAllowed(ctx,existing.orderId,orders,shipments);const row=await repository.lockById(ctx.tx,input.id);if(!row)throw PlatformError.notFound('Refund',input.id);if(row.status!=='failed')throw PlatformError.conflict(`Refund ${row.id} is not retryable (status=${row.status})`);const nextAttempt=row.attemptNo+1;const updated=await repository.update(ctx.tx,row.id,{status:'requested',attemptNo:nextAttempt,providerRequestRef:`refund:${row.id}:attempt:${nextAttempt}`,failureMessage:null,completedAt:null},ctx.now);const dto=toRefundDto(updated!);await ctx.publish({name:refundRequestedV1.name,payload:eventPayload(dto,ctx.now,row.paymentProviderRef)});return dto;};}
export const recordRefundResultCommand=defineCommand({name:'commerce.refund.recordRefundResult',summary:'記錄 provider 退款結果',input:recordRefundResultInput,output:refundDto,permission:'refund:provider-write',idempotency:'required',audit:{action:'refund.provider_result_recorded',resourceType:'refund',resourceId:i=>i.id,redact:i=>({paymentProvider:i.paymentProvider,status:i.status})}});
export function createRecordRefundResultHandler(orders:RefundOrderLookup){return async(input:z.infer<typeof recordRefundResultInput>,ctx:CommandContext):Promise<RefundDto>=>{if(ctx.actor.type!=='system')throw PlatformError.forbidden('Only a verified refund worker may record provider results');const existing=await repository.findById(ctx.tx,input.id);if(!existing)throw PlatformError.notFound('Refund',input.id);await orders.paymentForRefund(ctx.tx,existing.orderId);const row=await repository.lockById(ctx.tx,input.id);if(!row)throw PlatformError.notFound('Refund',input.id);if(row.paymentProvider!==input.paymentProvider||row.providerRequestRef!==input.providerRequestRef)throw PlatformError.conflict(`Refund ${row.id} does not match provider evidence`);if(row.status==='succeeded'){if(input.status!=='succeeded'||row.providerRefundRef!==input.providerRefundRef)throw PlatformError.conflict(`Refund ${row.id} already has a different terminal result`);return toRefundDto(row);}if(row.status==='failed')return toRefundDto(row);const updated=input.status==='succeeded'?await repository.update(ctx.tx,row.id,{status:'succeeded',providerRefundRef:input.providerRefundRef!,failureMessage:null,completedAt:ctx.now},ctx.now):await repository.update(ctx.tx,row.id,{status:'failed',failureMessage:input.failureMessage!,completedAt:ctx.now},ctx.now);const dto=toRefundDto(updated!);const payload=eventPayload(dto,ctx.now,row.paymentProviderRef);if(input.status==='succeeded'){if(dto.source==='direct')await orders.finalizeDirectRefund(ctx,dto.orderId);await ctx.publish({name:refundSucceededV1.name,payload});}else await ctx.publish({name:refundFailedV1.name,payload:{...payload,failureMessage:dto.failureMessage!}});return dto;};}
