import { randomUUID } from 'node:crypto';
import type { z } from 'zod';
import { PlatformError,defineCommand,type CommandContext,type Tx } from '@storeweave/contracts';
import { customerService } from '@storeweave/customer';
import { inventoryService } from '@storeweave/inventory';
import { createRmaRefund,type RefundDto } from '@storeweave/refund';
import { createRmaInput,receiveRmaInput,recordRmaRefundRequestedInput,recordRmaRefundResultInput,requestRmaRefundInput,rmaDto,staffRmaInput,type RmaDto } from './dto';
import { rmaRequestedV1,rmaStatusChangedV1 } from './events';
import { RmaRepository,toRmaDto } from './repository';
const repository=new RmaRepository();

export interface RmaOrderLookup { returnableForRma(tx:Tx,orderId:string):Promise<{orderId:string;customerId:string|null;currency:string;amountCents:number;paymentAttemptId:string;paymentAttemptRef:string;paymentProvider:string;paymentProviderRef:string;lines:readonly {id:string;productId:string;sku:string;name:string;quantity:number;unitPriceCents:number;lineTotalCents:number;discountCents:number}[]}>; }
export interface RmaShipmentLookup { hasReturnableShipment(tx:Tx,orderId:string):Promise<boolean>; }
const payload=(r:RmaDto,now:Date)=>({rmaId:r.id,orderId:r.orderId,occurredAt:now});
async function currentCustomer(ctx:CommandContext){if(ctx.actor.type!=='customer')throw PlatformError.forbidden('Only customers may create an RMA');const id=await customerService.customerIdOf(ctx.tx,ctx.actor);if(!id)throw PlatformError.forbidden('Customer profile is required to create an RMA');return id;}
async function locked(ctx:CommandContext,id:string){const row=await repository.lockById(ctx.tx,id);if(!row)throw PlatformError.notFound('RMA',id);return {row,lines:await repository.linesFor(ctx.tx,id)};}
async function transition(ctx:CommandContext,id:string,status:RmaDto['status'],values:Record<string,unknown>={}){const updated=await repository.update(ctx.tx,id,{status,...values} as any,ctx.now);if(!updated)throw PlatformError.notFound('RMA',id);const dto=toRmaDto(updated,await repository.linesFor(ctx.tx,id));await ctx.publish({name:rmaStatusChangedV1.name,payload:{...payload(dto,ctx.now),status}});return dto;}
export const createRmaCommand=defineCommand({name:'commerce.rma.createRma',summary:'顧客建立退貨案件',input:createRmaInput,output:rmaDto,permission:'rma:create',idempotency:'required',audit:{action:'rma.created',resourceType:'rma',resourceId:(_i,o:RmaDto)=>o.id,redact:i=>({orderId:i.orderId,reason:i.reason})}});
export function createCreateRmaHandler(orders:RmaOrderLookup,shipments:RmaShipmentLookup){return async(input:z.infer<typeof createRmaInput>,ctx:CommandContext):Promise<RmaDto>=>{const customerId=await currentCustomer(ctx);const order=await orders.returnableForRma(ctx.tx,input.orderId);if(order.customerId!==customerId)throw PlatformError.notFound('Order',input.orderId);if(!await shipments.hasReturnableShipment(ctx.tx,input.orderId))throw PlatformError.conflict('An RMA requires a shipped, arrived, or completed shipment');const requested=new Map<string,number>();for(const line of input.lines){if(requested.has(line.orderLineId))throw PlatformError.validation('Each order line may appear once');requested.set(line.orderLineId,line.quantity);}const selected:Array<(typeof order.lines)[number]>=[];for(const [lineId,quantity] of requested){const line=order.lines.find(candidate=>candidate.id===lineId);if(!line)throw PlatformError.validation(`Order line ${lineId} does not belong to this order`);const claimed=await repository.claimedQuantity(ctx.tx,line.id);if(quantity+claimed>line.quantity)throw PlatformError.conflict(`Return quantity exceeds purchased quantity for order line ${line.id}`);selected.push({...line,quantity});}const id=randomUUID();const row=await repository.insert(ctx.tx,{id,orderId:order.orderId,customerId,status:'requested',resolution:'refund_and_reorder',reason:input.reason,requestedByActorId:ctx.actor.id,createdAt:ctx.now,updatedAt:ctx.now});await repository.insertLines(ctx.tx,selected.map(line=>({id:randomUUID(),rmaId:id,orderLineId:line.id,productId:line.productId,sku:line.sku,name:line.name,unitPriceCents:line.unitPriceCents,lineTotalCents:line.lineTotalCents,discountCents:line.discountCents,quantity:line.quantity})));const dto=toRmaDto(row,await repository.linesFor(ctx.tx,id));await ctx.publish({name:rmaRequestedV1.name,payload:payload(dto,ctx.now)});return dto;};}
export const approveRmaCommand=defineCommand({name:'commerce.rma.approveRma',summary:'核准退貨案件',input:staffRmaInput,output:rmaDto,permission:'rma:write',idempotency:'required',audit:{action:'rma.approved',resourceType:'rma',resourceId:i=>i.id}});
export const requestRmaInformationCommand=defineCommand({name:'commerce.rma.requestInformation',summary:'要求補充退貨資料',input:staffRmaInput,output:rmaDto,permission:'rma:write',idempotency:'required',audit:{action:'rma.information_requested',resourceType:'rma',resourceId:i=>i.id}});
export const rejectRmaCommand=defineCommand({name:'commerce.rma.rejectRma',summary:'拒絕退貨案件',input:staffRmaInput,output:rmaDto,permission:'rma:write',idempotency:'required',audit:{action:'rma.rejected',resourceType:'rma',resourceId:i=>i.id}});
export const approveRmaHandler=async(input:z.infer<typeof staffRmaInput>,ctx:CommandContext)=>{const {row}=await locked(ctx,input.id);if(!['requested','needs_information'].includes(row.status))throw PlatformError.conflict(`RMA ${row.id} cannot be approved from ${row.status}`);return transition(ctx,row.id,'approved',{staffNote:input.note??null});};
export const requestRmaInformationHandler=async(input:z.infer<typeof staffRmaInput>,ctx:CommandContext)=>{const {row}=await locked(ctx,input.id);if(!['requested','approved'].includes(row.status))throw PlatformError.conflict(`RMA ${row.id} cannot request information from ${row.status}`);if(!input.note)throw PlatformError.validation('note is required when requesting information');return transition(ctx,row.id,'needs_information',{staffNote:input.note});};
export const rejectRmaHandler=async(input:z.infer<typeof staffRmaInput>,ctx:CommandContext)=>{const {row}=await locked(ctx,input.id);if(!['requested','needs_information','approved'].includes(row.status))throw PlatformError.conflict(`RMA ${row.id} cannot be rejected from ${row.status}`);if(!input.note)throw PlatformError.validation('note is required when rejecting an RMA');return transition(ctx,row.id,'rejected',{staffNote:input.note,completedAt:ctx.now});};
export const receiveRmaCommand=defineCommand({name:'commerce.rma.receiveRma',summary:'收件並處置退貨庫存',input:receiveRmaInput,output:rmaDto,permission:'rma:write',idempotency:'required',audit:{action:'rma.received',resourceType:'rma',resourceId:i=>i.id,redact:i=>({lineCount:i.lines.length})}});
export const receiveRmaHandler=async(input:z.infer<typeof receiveRmaInput>,ctx:CommandContext)=>{const {row,lines}=await locked(ctx,input.id);if(row.status!=='approved')throw PlatformError.conflict(`RMA ${row.id} cannot be received from ${row.status}`);if(new Set(input.lines.map(line=>line.rmaLineId)).size!==input.lines.length||input.lines.length!==lines.length||input.lines.some(line=>!lines.some(existing=>existing.id===line.rmaLineId)))throw PlatformError.validation('A disposition is required exactly once for every RMA line');for(const line of input.lines){const existing=lines.find(candidate=>candidate.id===line.rmaLineId)!;await repository.updateLine(ctx.tx,existing.id,{disposition:line.disposition,discardReason:line.disposition==='discard'?line.discardReason!:null});if(line.disposition==='restock')await inventoryService.adjust(ctx,{productId:existing.productId,delta:existing.quantity,reason:'rma-restock',reference:`rma:${row.id}`});}return transition(ctx,row.id,'received',{receivedAt:ctx.now});};
export const requestRmaRefundCommand=defineCommand({name:'commerce.rma.requestRefund',summary:'為已收件退貨案件建立退款',input:requestRmaRefundInput,output:rmaDto,permission:'rma:write',idempotency:'required',audit:{action:'rma.refund_requested',resourceType:'rma',resourceId:i=>i.id}});
export function createRequestRmaRefundHandler(orders:RmaOrderLookup){return async(input:z.infer<typeof requestRmaRefundInput>,ctx:CommandContext)=>{const {row,lines}=await locked(ctx,input.id);if(row.status!=='received')throw PlatformError.conflict(`RMA ${row.id} cannot request refund from ${row.status}`);const order=await orders.returnableForRma(ctx.tx,row.orderId);const amountCents=lines.reduce((sum,line)=>sum+Math.floor((line.lineTotalCents-line.discountCents)*line.quantity/(order.lines.find(candidate=>candidate.id===line.orderLineId)?.quantity??1)),0);if(amountCents<=0)throw PlatformError.conflict(`RMA ${row.id} has no refundable amount`);const refund:RefundDto=await createRmaRefund(ctx,{rmaId:row.id,orderId:order.orderId,customerId:order.customerId,currency:order.currency,amountCents,paymentAttemptId:order.paymentAttemptId,paymentAttemptRef:order.paymentAttemptRef,paymentProvider:order.paymentProvider,paymentProviderRef:order.paymentProviderRef,reason:input.reason??row.reason});return transition(ctx,row.id,'refund_pending',{refundId:refund.id});};}
export const recordRmaRefundResultCommand=defineCommand({name:'commerce.rma.recordRefundResult',summary:'同步退款結果至退貨案件',input:recordRmaRefundResultInput,output:rmaDto,permission:'rma:system-write',idempotency:'required',audit:{action:'rma.refund_result_recorded',resourceType:'rma',resourceId:i=>i.rmaId}});
export const recordRmaRefundRequestedCommand=defineCommand({name:'commerce.rma.recordRefundRequested',summary:'同步退款重試至退貨案件',input:recordRmaRefundRequestedInput,output:rmaDto,permission:'rma:system-write',idempotency:'required',audit:{action:'rma.refund_retry_recorded',resourceType:'rma',resourceId:i=>i.rmaId}});
export const recordRmaRefundRequestedHandler=async(input:z.infer<typeof recordRmaRefundRequestedInput>,ctx:CommandContext)=>{if(ctx.actor.type!=='system')throw PlatformError.forbidden('Only the refund worker may update an RMA');const {row}=await locked(ctx,input.rmaId);if(row.refundId!==input.refundId)throw PlatformError.conflict(`Refund ${input.refundId} does not belong to RMA ${row.id}`);if(row.status==='refund_pending')return toRmaDto(row,await repository.linesFor(ctx.tx,row.id));if(row.status==='refund_failed'&&input.attemptNo>1)return transition(ctx,row.id,'refund_pending',{});if(row.status==='refund_failed')return toRmaDto(row,await repository.linesFor(ctx.tx,row.id));throw PlatformError.conflict(`RMA ${row.id} cannot retry refund from ${row.status}`);};
export const recordRmaRefundResultHandler=async(input:z.infer<typeof recordRmaRefundResultInput>,ctx:CommandContext)=>{if(ctx.actor.type!=='system')throw PlatformError.forbidden('Only the refund result worker may update an RMA');const {row}=await locked(ctx,input.rmaId);if(row.refundId!==input.refundId)throw PlatformError.conflict(`Refund ${input.refundId} does not belong to RMA ${row.id}`);if(row.status==='completed'&&input.status==='succeeded')return toRmaDto(row,await repository.linesFor(ctx.tx,row.id));if(row.status==='refund_failed'&&input.status==='failed')return toRmaDto(row,await repository.linesFor(ctx.tx,row.id));if(row.status!=='refund_pending')throw PlatformError.conflict(`RMA ${row.id} cannot record a refund result from ${row.status}`);return transition(ctx,row.id,input.status==='succeeded'?'completed':'refund_failed',input.status==='succeeded'?{completedAt:ctx.now}:{});};
