#!/usr/bin/env node
import { releases } from './releases.mjs';
// 把 TypeScript 原始碼打包成正式主機可直接執行的 JavaScript。
// 正式主機不需要 pnpm、TypeScript 或任何編譯工具。
import { build } from 'esbuild';
import { execFileSync } from 'node:child_process';
import { cpSync, existsSync, mkdirSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const releaseId = process.env.STOREWEAVE_RELEASE ?? 'commerce';
if (!Object.hasOwn(releases, releaseId)) throw new Error(`Unknown release: ${releaseId}`);
const selected = releases[releaseId];
const outDir = process.env.STOREWEAVE_BUILD_DIR ? resolve(process.env.STOREWEAVE_BUILD_DIR) : join(root, 'dist');
if (process.env.STOREWEAVE_BUILD_DIR && existsSync(outDir)) throw new Error('STOREWEAVE_BUILD_DIR must be a new directory');
const appDir = join(outDir, 'app');
const version = process.env.STOREWEAVE_RELEASE_VERSION ?? process.env.COMMERCE_RELEASE_VERSION ?? JSON.parse(
  execFileSync('node', ['-p', 'JSON.stringify(require("./package.json"))'], { cwd: root, encoding: 'utf8' }),
).version;

const skipAdmin = !selected.admin || process.argv.includes('--skip-admin');

// NestJS 對這些套件都是「有裝才用」的 lazy require；我們沒有用到，因此標成 external。
// pg-native 是 pg 的選用原生加速套件，沒有它會自動走純 JS 路徑。
const EXTERNALS = [
  'pg-native',
  'class-transformer',
  'class-transformer/storage',
  'class-validator',
  'cache-manager',
  '@nestjs/websockets',
  '@nestjs/websockets/socket-module',
  '@nestjs/microservices',
  '@nestjs/microservices/microservices-module',
  '@nestjs/platform-express',
  '@fastify/view',
  '@fastify/middie',
];

rmSync(outDir, { recursive: true, force: true });
mkdirSync(appDir, { recursive: true });

const entries = [
  { in: join(root, 'apps/api/src/main.ts'), out: join(appDir, 'api.js') },
  { in: join(root, 'apps/worker/src/main.ts'), out: join(appDir, 'worker.js') },
  { in: join(root, 'tools/cli/src/main.ts'), out: join(appDir, 'cli.js') },
  { in: join(root, 'scripts/seed.ts'), out: join(appDir, 'seed.js') },
];
const manifestEntry = { in: join(root, 'scripts/release-manifest.ts'), out: join(outDir, 'release-manifest.js') };
const validatorEntry = { in: join(root, 'scripts/validate-release.ts'), out: join(outDir, 'scripts/validate-release.js') };
let manifestChecksum;

for (const entry of [manifestEntry, ...entries, validatorEntry]) {
  const result = await build({
    entryPoints: [entry.in],
    outfile: entry.out,
    bundle: true,
    metafile: true,
    define: {
      'process.env.STOREWEAVE_RELEASE_VERSION': JSON.stringify(version),
      ...(manifestChecksum ? { 'process.env.STOREWEAVE_BUILD_MANIFEST_SHA': JSON.stringify(manifestChecksum) } : {}),
    },
    alias: {
      '@storeweave/selected-release': join(root, selected.runtime),
      '@storeweave/selected-http': join(root, selected.http),
      '@storeweave/selected-seed': join(root, selected.seed),
    },
    platform: 'node',
    target: 'node22',
    format: 'cjs',
    sourcemap: true,
    minify: false,
    tsconfig: join(root, 'tsconfig.json'),
    // pg-native 是 pg 的選用原生加速套件；沒有它 pg 會自動走純 JS 路徑
    external: EXTERNALS,
    banner: { js: `// StoreWeave ${version} — generated by scripts/build.mjs, do not edit` },
    logLevel: 'info',
  });
  if (releaseId === 'base') {
    const forbidden = Object.keys(result.metafile.inputs).filter(file =>
      /(^|\/)packages\/(commerce|extensions)\//.test(file)
      || file.includes('packages/themes/default/')
      || file.endsWith('apps/api/src/releases/commerce.ts')
      || file.endsWith('scripts/seeds/commerce.ts'));
    if (forbidden.length) throw new Error(`Base bundle imports Commerce: ${forbidden.join(', ')}`);
  }
  writeFileSync(`${entry.out}.meta.json`, `${JSON.stringify(result.metafile, null, 2)}\n`);
  if (entry === manifestEntry) {
    const result = JSON.parse(execFileSync(process.execPath, [entry.out], { cwd: root, encoding: 'utf8' }));
    manifestChecksum = result.checksum;
    writeFileSync(join(outDir, 'release-manifest.json'), `${JSON.stringify(result.manifest, null, 2)}\n`);
    rmSync(entry.out);
    rmSync(`${entry.out}.map`);
  }

}

const adminEntry = join(root, 'apps/admin/index.html');
if (!skipAdmin && existsSync(adminEntry)) {
  execFileSync('npx', ['vite', 'build', '--config', 'apps/admin/vite.config.ts', '--outDir', join(outDir, 'admin')], { cwd: root, stdio: 'inherit' });
} else if (!skipAdmin) {
  console.warn('warning: apps/admin/index.html not found; skipping admin build');
}
const adminDist = join(root, 'apps/admin/dist');
if (selected.admin && skipAdmin && existsSync(adminDist)) {
  cpSync(adminDist, join(outDir, 'admin'), { recursive: true });
}

// Default Theme editorial media is a release-owned asset set. It is copied
// separately from the bundled JS so the storefront can serve it with ordinary
// HTTP caching rather than encoding image bytes into each SSR response.
const defaultThemeAssets = selected.themeAssets && join(root, selected.themeAssets);
if (defaultThemeAssets && existsSync(defaultThemeAssets)) {
  cpSync(defaultThemeAssets, join(outDir, 'theme-assets'), { recursive: true });
}

writeFileSync(join(outDir, 'VERSION'), `${version}\n`, 'utf8');
writeFileSync(
  join(outDir, 'build-info.json'),
  `${JSON.stringify({ releaseId, version, manifestChecksum, builtOnNode: process.version, entries: entries.map((e) => e.out.replace(root, '')) }, null, 2)}\n`,
  'utf8',
);

console.log(`\nbuilt ${version} -> ${outDir}`);
