#!/usr/bin/env node
// 把 TypeScript 原始碼打包成正式主機可直接執行的 JavaScript。
// 正式主機不需要 pnpm、TypeScript 或任何編譯工具。
import { build } from 'esbuild';
import { execFileSync } from 'node:child_process';
import { cpSync, existsSync, mkdirSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const outDir = join(root, 'dist');
const appDir = join(outDir, 'app');
const version = process.env.COMMERCE_RELEASE_VERSION ?? JSON.parse(
  execFileSync('node', ['-p', 'JSON.stringify(require("./package.json"))'], { cwd: root, encoding: 'utf8' }),
).version;

const skipAdmin = process.argv.includes('--skip-admin');

// NestJS 對這些套件都是「有裝才用」的 lazy require；我們沒有用到，因此標成 external。
// pg-native 是 pg 的選用原生加速套件，沒有它會自動走純 JS 路徑。
const EXTERNALS = [
  'pg-native',
  'class-transformer',
  'class-transformer/storage',
  'class-validator',
  'cache-manager',
  '@nestjs/websockets',
  '@nestjs/websockets/socket-module',
  '@nestjs/microservices',
  '@nestjs/microservices/microservices-module',
  '@nestjs/platform-express',
  '@fastify/view',
  '@fastify/middie',
];

rmSync(outDir, { recursive: true, force: true });
mkdirSync(appDir, { recursive: true });

const entries = [
  { in: join(root, 'apps/api/src/main.ts'), out: join(appDir, 'api.js') },
  { in: join(root, 'apps/worker/src/main.ts'), out: join(appDir, 'worker.js') },
  { in: join(root, 'tools/cli/src/main.ts'), out: join(appDir, 'cli.js') },
];

for (const entry of entries) {
  await build({
    entryPoints: [entry.in],
    outfile: entry.out,
    bundle: true,
    platform: 'node',
    target: 'node22',
    format: 'cjs',
    sourcemap: true,
    minify: false,
    tsconfig: join(root, 'tsconfig.json'),
    // pg-native 是 pg 的選用原生加速套件；沒有它 pg 會自動走純 JS 路徑
    external: EXTERNALS,
    banner: { js: `// StoreWeave ${version} — generated by scripts/build.mjs, do not edit` },
    logLevel: 'info',
  });
}

const adminEntry = join(root, 'apps/admin/index.html');
if (!skipAdmin && existsSync(adminEntry)) {
  execFileSync('npx', ['vite', 'build', '--config', 'apps/admin/vite.config.ts'], { cwd: root, stdio: 'inherit' });
} else if (!skipAdmin) {
  console.warn('warning: apps/admin/index.html not found; skipping admin build');
}
const adminDist = join(root, 'apps/admin/dist');
if (existsSync(adminDist)) {
  cpSync(adminDist, join(outDir, 'admin'), { recursive: true });
}

writeFileSync(join(outDir, 'VERSION'), `${version}\n`, 'utf8');
writeFileSync(
  join(outDir, 'build-info.json'),
  `${JSON.stringify({ version, builtOnNode: process.version, entries: entries.map((e) => e.out.replace(root, '')) }, null, 2)}\n`,
  'utf8',
);

console.log(`\nbuilt ${version} -> ${outDir}`);
