/** One build selection supplies process adapters and non-artifact runtime projections. */
export const releases = {
  base: {
    runtime: 'packages/releases/base/src/runtime.ts',
    server: 'packages/releases/base/src/server.ts',
    worker: 'packages/releases/base/src/worker.ts',
    adminProjection: 'packages/releases/base/src/admin.ts',
    cli: 'packages/releases/base/src/cli.ts',
    configProjection: 'packages/releases/base/src/config.ts',
    storefrontProjection: 'packages/releases/base/src/storefront.ts',
    seed: 'scripts/seeds/base.ts',
    admin: false,
    forbiddenInputs: ['packages/commerce', 'packages/extensions', 'packages/themes/default', 'packages/releases/commerce', 'apps/api/src/releases/commerce.ts', 'scripts/seeds/commerce.ts'],
    native: {
      name: 'storeweave',
      configFiles: [
        { source: 'deployments/storeweave.example.yaml', filename: 'storeweave.yaml.example' },
        { source: 'deployments/storeweave.env.example', filename: 'storeweave.env.example' },
      ],
      smokeScript: 'scripts/smoke-base.sh',
      apiService: 'deployments/systemd/storeweave-api.service',
      workerService: 'deployments/systemd/storeweave-worker.service',
    },
  },
  // B16 的模組範例：base 加上一個自己有資料表、前後台頁面與背景工作的非商務模組。
  'file-requests': {
    runtime: 'packages/examples/file-requests/src/runtime.ts',
    server: 'packages/examples/file-requests/src/server.ts',
    worker: 'packages/examples/file-requests/src/worker.ts',
    adminProjection: 'packages/examples/file-requests/src/admin.ts',
    cli: 'packages/examples/file-requests/src/cli.ts',
    configProjection: 'packages/examples/file-requests/src/config.ts',
    storefrontProjection: 'packages/examples/file-requests/src/storefront.ts',
    seed: 'scripts/seeds/file-requests.ts',
    admin: false,
    forbiddenInputs: ['packages/commerce', 'packages/extensions', 'packages/themes/default', 'packages/releases/commerce'],
    native: undefined,
  },
  commerce: {
    runtime: 'packages/releases/commerce/src/runtime.ts',
    server: 'packages/releases/commerce/src/server.ts',
    worker: 'packages/releases/commerce/src/worker.ts',
    adminProjection: 'packages/releases/commerce/src/admin.tsx',
    cli: 'packages/releases/commerce/src/cli.ts',
    configProjection: 'packages/releases/commerce/src/config.ts',
    storefrontProjection: 'packages/releases/commerce/src/storefront.ts',
    seed: 'scripts/seeds/commerce.ts',
    admin: true,
    native: {
      name: 'commerce',
      configFiles: [
        { source: 'deployments/example-store/commerce.yaml', filename: 'commerce.yaml.example' },
        { source: 'deployments/example-store/commerce.env.example', filename: 'commerce.env.example' },
        { source: 'deployments/example-store-two/commerce.yaml', filename: 'commerce.yaml.second-store-example' },
      ],
      smokeScript: 'scripts/smoke.sh',
      apiService: 'deployments/systemd/commerce-api.service',
      workerService: 'deployments/systemd/commerce-worker.service',
    },
  },
};
